### ISSUE TITLE
Markers API

### ISSUE THREAD

**Issue by romainmartinez** [romainmartinez/pyomeca#10]
Link: [Markers](https://romainmartinez.github.io/pyomeca/api/markers/)

**Comment by jdowlingmedley** [comment]
> Delimiter that split each column name by its prefix (we keep only the column name)
"Removes prefix from column name."

> Delimiter that split each column name by its suffix (we keep only the column name)
"Removes suffix from column name."

> Column of the time column. If None, we associate the index
"Location of the time column. If None, indices are associated."
