### ISSUE TITLE
DataArray Accessor

### ISSUE THREAD

**Issue by romainmartinez** [romainmartinez/pyomeca#11]
Link: [DataArray Accessor](https://romainmartinez.github.io/pyomeca/api/dataarray_accessor/)

**Comment by Dangzilla** [comment]
Add a capital ''A'' to ''Dataarray Accessor'' in the scrolldown menu on the left.

**Comment by jdowlingmedley** [comment]
> mean of the signal to subtract. If not provided, takes the mean along the time axis

would read better as "mean value of signal that will be subtracted. If unspecified, the mean is taken along the time axis."
