### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by romainmartinez** [romainmartinez/pyomeca#2]
Link: [Home](https://romainmartinez.github.io/pyomeca/)

- [x] Add contributors
- [x] Add binder badge
- [x] API exploration illustration
- [x] Add svg/gif of some analyses

**Comment by Dangzilla** [comment]
'' See Pyomeca's documentation site'' is a bit redundant. When I click on ''documentation site'', it simply brings me back to the same page. Maybe replace with ''Explore the different sections of this website for further documentation on Pyomeca.''?

**Comment by Dangzilla** [comment]
''See the documentation for more details and examples.'' -- same comment as previous one. I feel like it's redundant as it brings me back to the same page. Replace with ''Additional detail and examples can be found in the different sections of this website''.

**Comment by romainmartinez** [comment]
Absolutely, you make a good point. I had put a link to the documentation because the home page of the site is actually the [README.md](https://github.com/romainmartinez/pyomeca) of the repo github.
I fixed the problem in [5645a62](https://github.com/romainmartinez/pyomeca/commit/5645a62c585a1ee25ff1bffdd5ee6e343765b21b) and there's no more link to the documentation when you're already in it.
