### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by romainmartinez** [romainmartinez/pyomeca#3]
Link: [Overview](https://romainmartinez.github.io/pyomeca/overview/)

- [x] Fix tooltip position
- [x] Fix link to API

**Comment by Dangzilla** [comment]
''Select values by labels (array.sel(axis="x") or emg.sel(channel="biceps"))'' - Add a period at the end of the sentence

**Comment by Dangzilla** [comment]
''Object creation with the from_* methods. For example, if you want to define a marker array from a csv file: markers = Markers.from_csv(...).'' - When I click on ''Object creation'', it brings me to a _Page Not Found_

**Comment by Dangzilla** [comment]
''Data processing with the meca array accessor. To low-pass filter our previous markers: markers.meca.low_pass(...).'' - When I click on ''Data processing'', it brings me to a _Page Not Found_

**Comment by romainmartinez** [comment]
Done :+1:

**Comment by Dangzilla** [comment]
"Hover the mouse over any block to display a short description with some examples and click to jump to the corresponding API reference." - Broken links when I click on each block.

**Comment by jdowlingmedley** [comment]
In my browser the text "Joint Angles Matrix" and "Example with 3 axes, 2 degrees of freedom and 5 time frames" are superimposed/overlap. 
![Screen Shot 2020-04-24 at 10 39 50 AM](https://user-images.githubusercontent.com/54327782/80224662-fc17a800-8617-11ea-8c5e-fef360a464f5.png)
