### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by romainmartinez** [romainmartinez/pyomeca#4]
Link: [Getting Started](https://romainmartinez.github.io/pyomeca/getting-started/)

- [x] Dask
- [x] Fix import in Binder

**Comment by Dangzilla** [comment]
''There are several ways to create objects in pyomeca: by supplying data, from files or from other data-structure. A more complete guide on object creation is available in the objection creation section of the documentation.'' - _Page Not Found_ for the link + replace objection with object?

**Comment by Dangzilla** [comment]
''For more details, see the data processing section of the documentation.''  - _Page Not Found_ for the link
