### ISSUE TITLE
User Guide - Data Processing

### ISSUE THREAD

**Issue by romainmartinez** [romainmartinez/pyomeca#6]
Link: [Data Processing](https://pyomeca.github.io/data-processing/)

**Comment by Dangzilla** [comment]
DataArrayAccessor table is not the same font as the rest of the page

**Comment by Dangzilla** [comment]
These features can be broadly grouped into different categories: the filtering, normalization, linear algebra, signal processing and file io functions. --- I would remove ''the'' from ''the filtering''

**Comment by Dangzilla** [comment]
While the netcdf format is the preferred file format for saving or sharing data structures, Pyomeca also support writting csv and matlab file. Add an ''s'' to support(s) and file(s)

**Comment by romainmartinez** [comment]
> DataArrayAccessor table is not the same font as the rest of the page

@Dangzilla is it fixed now?

**Comment by Dangzilla** [comment]
@romainmartinez Yes it is fixed!
