### ISSUE TITLE
About

### ISSUE THREAD

**Issue by romainmartinez** [romainmartinez/pyomeca#7]
Link: [About](https://romainmartinez.github.io/pyomeca/about/)

**Comment by romainmartinez** [comment]
Add contributors:
- Benjamin
- Ariane
- Jenn

**Comment by Dangzilla** [comment]
''If you use pyomeca in your academic work, please consider citing our paper as:'' - redundant link as it brings back to same page.

**Comment by Dangzilla** [comment]
Thank you very mcuh for including me in the contributors! Here's my GitHub page if you want to link it: https://github.com/Dangzilla
